#This is web's dockerfiles and compose.
version: '2'
services:
        redis:
                image: redis
                expose: 
                        - "6379"
                restart: always
                ports:
                        - "6379:6379"
                container_name: redis_server
        db:
                image: docker.io/mysql:5.6
                expose: 
                        - "3306"
                restart: always
                ports:
                        - "3306:3306"
                container_name: db_server
                environment:
                        TZ: Asia/Shanghai
                        MYSQL_ROOT_PASSWORD: sjh080815
        web:
                build: ./tomcat
                expose: 
                        - "8080"
                restart: always
                links:
                        - redis
                        - db   
                ports:
                        - "8080:8080"
                container_name: bbs_server
                depends_on:
                        - redis
                        - db
        proxy:
                image: nginx
                volumes: 
                    - $PWD/conf:/etc/nginx/conf.d
                container_name: proxy
                expose: 
                    - "80"
                ports: 
                    - "80:80"
                depends_on:
                        - web
        
                
                    
                
                

