#This is web's dockerfiles and compose.
version: '2'
services:
        redis:
                image: redis
                expose: 
                        - "6379"
                restart: always
                ports:
                        - "6379:6379"
                container_name: redis_server
                volumes:
                        - $PWD/conf/redis.conf:/etc/redis/redis.conf
                        - $PWD/data/:/data/
                command: redis-server /etc/redis/redis.conf --appendonly yes
        db:
                image: docker.io/mysql:5.6
                expose: 
                        - "3306"
                restart: always
                ports:
                        - "3306:3306"
                container_name: db_server
                environment:
                        TZ: Asia/Shanghai
                        MYSQL_ROOT_PASSWORD: sjh080815
        web_1:
                image: java:8
                volumes:
                    - $PWD/tomcat/webapp:/web
                expose:
                    - "8080"
                container_name: bbs_server_1
                depends_on:
                        - redis
                        - db
                command: java -jar /web/forum-1.0-SNAPSHOT.jar
        web_2:
                image: java:8
                volumes:
                    - $PWD/tomcat/webapp:/web
                expose:
                    - "8080"
                container_name: bbs_server_2
                depends_on:
                        - redis
                        - db
                command: java -jar /web/forum-1.0-SNAPSHOT.jar
        proxy:
                image: nginx
                volumes: 
                    - $PWD/conf/default.conf:/etc/nginx/conf.d/default.conf
                    - $PWD/conf/cms.conf:/etc/nginx/conf.d/cms.conf
                    - $PWD/conf/bbs.conf:/etc/nginx/conf.d/bbs.conf
                container_name: proxy
                expose: 
                    - "80"
                ports: 
                    - "80:80"
                depends_on:
                        - web_1
                        - web_2
                
